#!/bin/bash

echo "Running Prosoul"

git clone https://github.com/Bitergia/prosoul.git
cd prosoul/django-prosoul/
# Fill the secret key, debug false and allow hosts
./config_deployment.py

# Create the data models
python3 manage.py makemigrations
python3 manage.py migrate

# Create the initial admin user: admin/admin
PYTHONPATH=. django_prosoul/create_admin_superuser.py

# Import some quality models as samples
PYTHONPATH=. prosoul/prosoul_import.py -f prosoul/data/ossmeter_qm.json --format ossmeter
PYTHONPATH=. prosoul/prosoul_import.py -f prosoul/data/alambic_quality_model.json --format alambic
PYTHONPATH=. prosoul/prosoul_import.py -f prosoul/data/basic_maturiy_model.json --format grimoirelab


# Run the Prosoul service
python3 manage.py runserver 0.0.0.0:8000
# There is an issue with gunicorn finding static contents
# gunicorn django_prosoul.wsgi --bind 0.0.0.0:8000
