#!/bin/bash

echo "Running Prosoul"
REPOSRC=https://github.com/Bitergia/prosoul.git
LOCALREPO=prosoul/django-prosoul/

if [ ! -d $LOCALREPO ]
then
    git clone $REPOSRC
fi

cd $LOCALREPO

# Set exec permission for config_deployment.py
sudo chmod 770 config_deployment.py

# debug false and allow hosts
./config_deployment.py

# Create the data models
python3 manage.py makemigrations
python3 manage.py migrate

# Create the initial admin user: admin/admin
PYTHONPATH=. django_prosoul/create_admin_superuser.py

# Import some quality models as samples
PYTHONPATH=. prosoul/prosoul_import.py -f prosoul/data/ossmeter_qm.json --format ossmeter
PYTHONPATH=. prosoul/prosoul_import.py -f prosoul/data/alambic_quality_model.json --format alambic
PYTHONPATH=. prosoul/prosoul_import.py -f prosoul/data/basic_maturiy_model.json --format grimoirelab
PYTHONPATH=. prosoul/prosoul_import.py -f prosoul/data/qmodel_crossminer.json


# Run the Prosoul service
python3 manage.py runserver 0.0.0.0:8000
# There is an issue with gunicorn finding static contents
# gunicorn django_prosoul.wsgi --bind 0.0.0.0:8000
